### ISSUE TITLE
The "Add M5Stack" button on the status bar goes away and I can't get it back

### ISSUE THREAD

**Issue by jjimsooter** [curdeveryday/vscode-m5stack-mpy#7] opened 2021-02-13 21:10 UTC
Issue Type: <b>Bug</b>

I have Disabled, Uninstall the extention, vscode, the com port - nothing works
if anyone have an idea please let me know
I am new to VSCode but I have been a developer for a long time

Extension version: 1.0.7
VS Code version: Code 1.53.2 (622cb03f7e070a9670c94bae1a45d78d7181fbd4, 2021-02-11T11:48:04.245Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4650U CPU @ 1.70GHz (4 x 2295)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.91GB (1.49GB free)|
|Process Argv|--crash-reporter-id ece940ff-72b0-43ee-a275-f93dbe2cfefd|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt617cf:30253240
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244cf:30256637
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt600cf:30251589

```

</details>

**Comment by gramjoue** [comment] 2021-02-15 16:23
I have the same problem @jjimsooter

-------------------
System Info:
> Extension version: 1.07
> VSCode on Linux Mint OS:
> Version: 1.53.2
> Commit: 622cb03f7e070a9670c94bae1a45d78d7181fbd4
> Date: 2021-02-11T11:48:44.518Z
> Electron: 11.2.1
> Chrome: 87.0.4280.141
> Node.js: 12.18.3
> V8: 8.7.220.31-electron.0
> OS: Linux x64 5.4.0-65-generic

**Comment by steffenu** [comment] 2021-02-17 09:13
same ....

**Comment by jarl-dk** [comment] 2021-02-23 12:02
This seems to be a duplicate of issue #6

**Closed** 2021-05-17 01:41 UTC
